# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

language: rust

rust:
  # - stable
  # - beta
  - nightly

env:
  - RELEASE_BUILD=--release
  - RELEASE_BUILD=

before_install:
  - rustup self update

# matrix:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true

script:
  - cargo build $RELEASE_BUILD --verbose
  - cargo test $RELEASE_BUILD --verbose

jobs:
  include:
  - stage: lint
    before_install: 
      - rustup component add clippy
      - rustup component add rustfmt
    script: cargo fmt -- --check 

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
